//<auto-generated />
namespace Popkultulista.Controllers;

using Microsoft.AspNetCore.Mvc;
using Popkultulista.Domain.Models;

/// <summary>
/// A controller for <see cref="Item"/>s.
/// </summary>
public class ItemController : Controller
{
    /// <summary>
    /// GET: ItemController
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public ActionResult Index()
    {
        ViewData["ItemName"] = "Itemek";
        return View();
    }

    /// <summary>
    /// GET: ItemController/Details/5
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public ActionResult Details(int id)
    {
        ViewBag.ItemTitle = "Szczegóły";
        return View();
    }

    /// <summary>
    /// GET: ItemController/Create
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public ActionResult Create()
    {
        string title = "Dodawanie";
        return View("Create", title);
    }

    /// <summary>
    /// POST: ItemController/Create
    /// </summary>
    /// <param name="collection"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }

    /// <summary>
    /// GET: ItemController/Edit/5
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    
    [HttpGet]
    public ActionResult Edit(int id)
    {
        return View();
    }

    /// <summary>
    /// POST: ItemController/Edit/5
    /// </summary>
    /// <param name="id"></param>
    /// <param name="collection"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }

    /// <summary>
    /// GET: ItemController/Delete/5
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public ActionResult Delete(int id)
    {
        return View();
    }

    /// <summary>
    /// POST: ItemController/Delete/5
    /// </summary>
    /// <param name="id"></param>
    /// <param name="collection"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }
}