//<auto-generated />
namespace Popkultulista.Controllers;
using Microsoft.AspNetCore.Mvc;
using Popkultulista.Domain.Models;

/// <summary>
/// A controller for <see cref="List"/>s.
/// </summary>
public class ListController : Controller
{
    /// <summary>
    /// GET: ListController
    /// </summary>
    /// <returns></returns>

    [HttpGet]
    public ActionResult Index()
    {
        return View();
    }

    /// <summary>
    /// GET: ListController/Details/5
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>

    [HttpGet]
    public ActionResult Details(int id)
    {
        return View();
    }

    /// <summary>
    /// GET: ListController/Create
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public ActionResult Create()
    {
        return View();
    }

    /// <summary>
    /// POST: ListController/Create
    /// </summary>
    /// <param name="collection"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }

    /// <summary>
    /// GET: ListController/Edit/5
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public ActionResult Edit(int id)
    {
        return View();
    }

    /// <summary>
    /// POST: ListController/Edit/5
    /// </summary>
    /// <param name="id"></param>
    /// <param name="collection"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }

    /// <summary>
    /// GET: ListController/Delete/5
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public ActionResult Delete(int id)
    {
        return View();
    }

    /// <summary>
    /// POST: ListController/Delete/5
    /// </summary>
    /// <param name="id"></param>
    /// <param name="collection"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }
}