//<auto-generated />
namespace Popkultulista.Controllers;

using Microsoft.AspNetCore.Mvc;
using Popkultulista.Domain.Models.Identity;

/// <summary>
/// A controller for <see cref="User"/>s
/// </summary>
public class UserController : Controller
{
    /// <summary>
    /// GET: UserController
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public ActionResult Index()
    {
        return View();
    }

    /// <summary>
    /// GET: UserController/Details/5
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public ActionResult Details(int id)
    {
        return View();
    }

    /// <summary>
    /// GET: UserController/Create
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public ActionResult Create()
    {
        return View();
    }

    /// <summary>
    /// POST: UserController/Create
    /// </summary>
    /// <param name="collection"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }

    /// <summary>
    /// GET: UserController/Edit/5
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public ActionResult Edit(int id)
    {
        return View();
    }

    /// <summary>
    /// POST: UserController/Edit/5
    /// </summary>
    /// <param name="id"></param>
    /// <param name="collection"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }

    /// <summary>
    /// GET: UserController/Delete/5
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public ActionResult Delete(int id)
    {
        return View();
    }

    /// <summary>
    /// POST: UserController/Delete/5
    /// </summary>
    /// <param name="id"></param>
    /// <param name="collection"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }
}